### ISSUE TITLE
There are no proofreaders for russian language. Without proofreaders translation isn't possible.

### ISSUE THREAD

**Issue by cienpascal** [ancap-ch/from-en#1890] opened 2018-03-02 08:48 UTC
I am proposing myself as a proofreader for russian. Only because there is no one else (i think) for this job. I just want to translate, but without someone to approve (or reject) my translations I am not able to continue.

**Comment by cienpascal** [comment] 2018-03-02 08:51
My pull request #1753

**Comment by SergZas** [comment] 2018-03-02 17:46
Yes, there is someone else to be a proofreader for Russian. Me. The problem is that the owner is now busy reorganizing the way how future translations and proofreading will be done. At least in some languages, including Russian. 

Я сам уже подавал несколько переводов, но приостановил работу и жду пока менеджер проекта решит все вопросы по дальнейшей организации процесса перевода.  

К вам такой вопрос: Вы используете ручной перевод или?

**Comment by cienpascal** [comment] 2018-03-02 20:52
That's great. Actually, I don't want to be a proofreader at all. Glad to have you here. Now I hope reorganization won't take too long.

Перевожу вручную, других способов пока не знаю. Разве что через переводчик. Если что, первые 20 "строк" переводил не я. И судя по всему именно вторым способом.

Если можно, скажите устраивает ли мой. Начинается с "Теперь:". Перевод пока грубоват. Планирую подправить, как закончу книгу.

Thanks for your time. :)

**Comment by swfsql** [comment] 2019-05-02 15:16
Sorry for taking so long to respond. I was trying to cross-check against various translation platforms incoming translations while trying to build-up trust on proofreaders candidates.

Translating depend a lot on proofreaders for unknown new and incoming translators, and those skills are very out of my reach.

As this project stalled and separated from utopian, I'll be closing this for now.
I appreciate your work on it!

**Closed by swfsql** 2019-05-02 15:16 UTC
